#ifndef HASHING_DEPENDIENTE_CLAVE_CONTROLLER_H_INCLUDED
#define HASHING_DEPENDIENTE_CLAVE_CONTROLLER_H_INCLUDED

#include "hashing_dependiente_clave.h"

#include "readFile.h"

void ejercicio2();

#endif // HASHING_DEPENDIENTE_CLAVE_CONTROLLER_H_INCLUDED
